### ISSUE TITLE
LuckPerms red in /plugins Please fix

### ISSUE THREAD

**Issue by FoxForFriends** [LuckPerms/wiki#110]
When using https://www.spigotmc.org/resources/luckperms.28140/ luckperms it is not working
Any reason or way to fix this?

**Comment by FoxForFriends** [comment]
I will go back to groupmanager for time being

**Comment by Turbotailz** [comment]
1. wrong repository, you should be opening an issue on [lucko/LuckPerms](https://github.com/lucko/LuckPerms) - this repo is for the Wiki
2. whenever a plugin doesn't work, you should always check the console for errors (and share them if you don't understand what the issue is)

**Comment by FoxForFriends** [comment]
Why should I move back if the one I have working is fine?

**Comment by FoxForFriends** [comment]
so when will luckperms be updated on spigot?
