### ISSUE TITLE
Wiki contains example code that only works on v4's API

### ISSUE THREAD

**Issue by TehBrian** [LuckPerms/wiki#28]
For example, https://github.com/LuckPerms/wiki/blob/master/Developer-API:-Usage.md#the-basics-of-cacheddata. In the `Obtaining PermissionData and MetaData` you can see this line: `MetaData metaData = user.getCachedData().getMetaData(contexts);`. However in v5's API `getCachedData()#getMetaData` only accepts QueryOptions as an argument. Additionally, the `Contexts` class doesn't exist anymore. As a matter of fact, there's not even a `MetaData` class anymore! I believe that has been replaced by `CachedMetaData`.

It would be helpful if the wiki could be updated to accurately reflect the usage of v5.

Apologies if this is already being worked on, I don't mean to rush. Thank you :)

**Comment by lucko** [comment]
Mostly fixed by #29
