### ISSUE TITLE
Create separate page/section for installation on Velocity?

### ISSUE THREAD

**Issue by Andre601** [LuckPerms/wiki#41]
I'm not sure how different Velocity is from BungeeCord in terms of installation, but I know that it has some major differences compared to Bungee in terms of API and configuration (i.e. it uses the TOML format and not yaml for the main config)

I open this issue, so that we could perhaps discuss this?
I think it would be worth considering making a separate section in the network installation guide, which explains the key differences between Velocity and Bungee, and perhaps also point out specific differences in configuration of LP, if there are any.

**Comment by lucko** [comment]
There's no real difference in terms of LP setup & configuration.

The Velocity documentation would be a better place to list differences with BungeeCord, if they wanted to.
